// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lm.proto

#ifndef PROTOBUF_lm_2eproto__INCLUDED
#define PROTOBUF_lm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace lm {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_lm_2eproto();
void protobuf_InitDefaults_lm_2eproto();
void protobuf_AssignDesc_lm_2eproto();
void protobuf_ShutdownFile_lm_2eproto();

class UserInfo_msg;
class chat_msg;
class connected_msg;
class join_room_msg;
class leave_room_msg;
class net_msg;
class sit_msg;

// ===================================================================

class connected_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.connected_msg) */ {
 public:
  connected_msg();
  virtual ~connected_msg();

  connected_msg(const connected_msg& from);

  inline connected_msg& operator=(const connected_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const connected_msg& default_instance();

  static const connected_msg* internal_default_instance();

  void Swap(connected_msg* other);

  // implements Message ----------------------------------------------

  inline connected_msg* New() const { return New(NULL); }

  connected_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const connected_msg& from);
  void MergeFrom(const connected_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(connected_msg* other);
  void UnsafeMergeFrom(const connected_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 cmd = 1;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 1;
  ::google::protobuf::int32 cmd() const;
  void set_cmd(::google::protobuf::int32 value);

  // required int32 from_id = 2;
  bool has_from_id() const;
  void clear_from_id();
  static const int kFromIdFieldNumber = 2;
  ::google::protobuf::int32 from_id() const;
  void set_from_id(::google::protobuf::int32 value);

  // required int32 recv_id = 3;
  bool has_recv_id() const;
  void clear_recv_id();
  static const int kRecvIdFieldNumber = 3;
  ::google::protobuf::int32 recv_id() const;
  void set_recv_id(::google::protobuf::int32 value);

  // required string msg = 4;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 4;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:lm.connected_msg)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();
  inline void set_has_from_id();
  inline void clear_has_from_id();
  inline void set_has_recv_id();
  inline void clear_has_recv_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 cmd_;
  ::google::protobuf::int32 from_id_;
  ::google::protobuf::int32 recv_id_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<connected_msg> connected_msg_default_instance_;

// -------------------------------------------------------------------

class net_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.net_msg) */ {
 public:
  net_msg();
  virtual ~net_msg();

  net_msg(const net_msg& from);

  inline net_msg& operator=(const net_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const net_msg& default_instance();

  static const net_msg* internal_default_instance();

  void Swap(net_msg* other);

  // implements Message ----------------------------------------------

  inline net_msg* New() const { return New(NULL); }

  net_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const net_msg& from);
  void MergeFrom(const net_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(net_msg* other);
  void UnsafeMergeFrom(const net_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 v = 1;
  bool has_v() const;
  void clear_v();
  static const int kVFieldNumber = 1;
  ::google::protobuf::int32 v() const;
  void set_v(::google::protobuf::int32 value);

  // required int32 m_id = 2;
  bool has_m_id() const;
  void clear_m_id();
  static const int kMIdFieldNumber = 2;
  ::google::protobuf::int32 m_id() const;
  void set_m_id(::google::protobuf::int32 value);

  // required int32 s_id = 3;
  bool has_s_id() const;
  void clear_s_id();
  static const int kSIdFieldNumber = 3;
  ::google::protobuf::int32 s_id() const;
  void set_s_id(::google::protobuf::int32 value);

  // required int32 opt = 4;
  bool has_opt() const;
  void clear_opt();
  static const int kOptFieldNumber = 4;
  ::google::protobuf::int32 opt() const;
  void set_opt(::google::protobuf::int32 value);

  // optional string data = 5;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 5;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:lm.net_msg)
 private:
  inline void set_has_v();
  inline void clear_has_v();
  inline void set_has_m_id();
  inline void clear_has_m_id();
  inline void set_has_s_id();
  inline void clear_has_s_id();
  inline void set_has_opt();
  inline void clear_has_opt();
  inline void set_has_data();
  inline void clear_has_data();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::int32 v_;
  ::google::protobuf::int32 m_id_;
  ::google::protobuf::int32 s_id_;
  ::google::protobuf::int32 opt_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<net_msg> net_msg_default_instance_;

// -------------------------------------------------------------------

class chat_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.chat_msg) */ {
 public:
  chat_msg();
  virtual ~chat_msg();

  chat_msg(const chat_msg& from);

  inline chat_msg& operator=(const chat_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const chat_msg& default_instance();

  static const chat_msg* internal_default_instance();

  void Swap(chat_msg* other);

  // implements Message ----------------------------------------------

  inline chat_msg* New() const { return New(NULL); }

  chat_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const chat_msg& from);
  void MergeFrom(const chat_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(chat_msg* other);
  void UnsafeMergeFrom(const chat_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 from_id = 1;
  bool has_from_id() const;
  void clear_from_id();
  static const int kFromIdFieldNumber = 1;
  ::google::protobuf::int32 from_id() const;
  void set_from_id(::google::protobuf::int32 value);

  // required int32 recv_id = 2;
  bool has_recv_id() const;
  void clear_recv_id();
  static const int kRecvIdFieldNumber = 2;
  ::google::protobuf::int32 recv_id() const;
  void set_recv_id(::google::protobuf::int32 value);

  // required string msg = 3;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 3;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:lm.chat_msg)
 private:
  inline void set_has_from_id();
  inline void clear_has_from_id();
  inline void set_has_recv_id();
  inline void clear_has_recv_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 from_id_;
  ::google::protobuf::int32 recv_id_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<chat_msg> chat_msg_default_instance_;

// -------------------------------------------------------------------

class join_room_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.join_room_msg) */ {
 public:
  join_room_msg();
  virtual ~join_room_msg();

  join_room_msg(const join_room_msg& from);

  inline join_room_msg& operator=(const join_room_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const join_room_msg& default_instance();

  static const join_room_msg* internal_default_instance();

  void Swap(join_room_msg* other);

  // implements Message ----------------------------------------------

  inline join_room_msg* New() const { return New(NULL); }

  join_room_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const join_room_msg& from);
  void MergeFrom(const join_room_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(join_room_msg* other);
  void UnsafeMergeFrom(const join_room_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 u_id = 1;
  bool has_u_id() const;
  void clear_u_id();
  static const int kUIdFieldNumber = 1;
  ::google::protobuf::int32 u_id() const;
  void set_u_id(::google::protobuf::int32 value);

  // required string msg = 2;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:lm.join_room_msg)
 private:
  inline void set_has_u_id();
  inline void clear_has_u_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 u_id_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<join_room_msg> join_room_msg_default_instance_;

// -------------------------------------------------------------------

class leave_room_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.leave_room_msg) */ {
 public:
  leave_room_msg();
  virtual ~leave_room_msg();

  leave_room_msg(const leave_room_msg& from);

  inline leave_room_msg& operator=(const leave_room_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const leave_room_msg& default_instance();

  static const leave_room_msg* internal_default_instance();

  void Swap(leave_room_msg* other);

  // implements Message ----------------------------------------------

  inline leave_room_msg* New() const { return New(NULL); }

  leave_room_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const leave_room_msg& from);
  void MergeFrom(const leave_room_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(leave_room_msg* other);
  void UnsafeMergeFrom(const leave_room_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 u_id = 1;
  bool has_u_id() const;
  void clear_u_id();
  static const int kUIdFieldNumber = 1;
  ::google::protobuf::int32 u_id() const;
  void set_u_id(::google::protobuf::int32 value);

  // required string msg = 2;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:lm.leave_room_msg)
 private:
  inline void set_has_u_id();
  inline void clear_has_u_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 u_id_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<leave_room_msg> leave_room_msg_default_instance_;

// -------------------------------------------------------------------

class sit_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.sit_msg) */ {
 public:
  sit_msg();
  virtual ~sit_msg();

  sit_msg(const sit_msg& from);

  inline sit_msg& operator=(const sit_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const sit_msg& default_instance();

  static const sit_msg* internal_default_instance();

  void Swap(sit_msg* other);

  // implements Message ----------------------------------------------

  inline sit_msg* New() const { return New(NULL); }

  sit_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const sit_msg& from);
  void MergeFrom(const sit_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(sit_msg* other);
  void UnsafeMergeFrom(const sit_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 u_id = 1;
  bool has_u_id() const;
  void clear_u_id();
  static const int kUIdFieldNumber = 1;
  ::google::protobuf::int32 u_id() const;
  void set_u_id(::google::protobuf::int32 value);

  // required string msg = 2;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:lm.sit_msg)
 private:
  inline void set_has_u_id();
  inline void clear_has_u_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 u_id_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<sit_msg> sit_msg_default_instance_;

// -------------------------------------------------------------------

class UserInfo_msg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:lm.UserInfo_msg) */ {
 public:
  UserInfo_msg();
  virtual ~UserInfo_msg();

  UserInfo_msg(const UserInfo_msg& from);

  inline UserInfo_msg& operator=(const UserInfo_msg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserInfo_msg& default_instance();

  static const UserInfo_msg* internal_default_instance();

  void Swap(UserInfo_msg* other);

  // implements Message ----------------------------------------------

  inline UserInfo_msg* New() const { return New(NULL); }

  UserInfo_msg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const UserInfo_msg& from);
  void MergeFrom(const UserInfo_msg& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(UserInfo_msg* other);
  void UnsafeMergeFrom(const UserInfo_msg& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 u_age = 1;
  bool has_u_age() const;
  void clear_u_age();
  static const int kUAgeFieldNumber = 1;
  ::google::protobuf::int32 u_age() const;
  void set_u_age(::google::protobuf::int32 value);

  // required int32 u_sex = 2;
  bool has_u_sex() const;
  void clear_u_sex();
  static const int kUSexFieldNumber = 2;
  ::google::protobuf::int32 u_sex() const;
  void set_u_sex(::google::protobuf::int32 value);

  // required string u_name = 3;
  bool has_u_name() const;
  void clear_u_name();
  static const int kUNameFieldNumber = 3;
  const ::std::string& u_name() const;
  void set_u_name(const ::std::string& value);
  void set_u_name(const char* value);
  void set_u_name(const char* value, size_t size);
  ::std::string* mutable_u_name();
  ::std::string* release_u_name();
  void set_allocated_u_name(::std::string* u_name);

  // required string u_address = 4;
  bool has_u_address() const;
  void clear_u_address();
  static const int kUAddressFieldNumber = 4;
  const ::std::string& u_address() const;
  void set_u_address(const ::std::string& value);
  void set_u_address(const char* value);
  void set_u_address(const char* value, size_t size);
  ::std::string* mutable_u_address();
  ::std::string* release_u_address();
  void set_allocated_u_address(::std::string* u_address);

  // @@protoc_insertion_point(class_scope:lm.UserInfo_msg)
 private:
  inline void set_has_u_age();
  inline void clear_has_u_age();
  inline void set_has_u_sex();
  inline void clear_has_u_sex();
  inline void set_has_u_name();
  inline void clear_has_u_name();
  inline void set_has_u_address();
  inline void clear_has_u_address();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr u_name_;
  ::google::protobuf::internal::ArenaStringPtr u_address_;
  ::google::protobuf::int32 u_age_;
  ::google::protobuf::int32 u_sex_;
  friend void  protobuf_InitDefaults_lm_2eproto_impl();
  friend void  protobuf_AddDesc_lm_2eproto_impl();
  friend void protobuf_AssignDesc_lm_2eproto();
  friend void protobuf_ShutdownFile_lm_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<UserInfo_msg> UserInfo_msg_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// connected_msg

// required int32 cmd = 1;
inline bool connected_msg::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void connected_msg::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void connected_msg::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void connected_msg::clear_cmd() {
  cmd_ = 0;
  clear_has_cmd();
}
inline ::google::protobuf::int32 connected_msg::cmd() const {
  // @@protoc_insertion_point(field_get:lm.connected_msg.cmd)
  return cmd_;
}
inline void connected_msg::set_cmd(::google::protobuf::int32 value) {
  set_has_cmd();
  cmd_ = value;
  // @@protoc_insertion_point(field_set:lm.connected_msg.cmd)
}

// required int32 from_id = 2;
inline bool connected_msg::has_from_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void connected_msg::set_has_from_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void connected_msg::clear_has_from_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void connected_msg::clear_from_id() {
  from_id_ = 0;
  clear_has_from_id();
}
inline ::google::protobuf::int32 connected_msg::from_id() const {
  // @@protoc_insertion_point(field_get:lm.connected_msg.from_id)
  return from_id_;
}
inline void connected_msg::set_from_id(::google::protobuf::int32 value) {
  set_has_from_id();
  from_id_ = value;
  // @@protoc_insertion_point(field_set:lm.connected_msg.from_id)
}

// required int32 recv_id = 3;
inline bool connected_msg::has_recv_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void connected_msg::set_has_recv_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void connected_msg::clear_has_recv_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void connected_msg::clear_recv_id() {
  recv_id_ = 0;
  clear_has_recv_id();
}
inline ::google::protobuf::int32 connected_msg::recv_id() const {
  // @@protoc_insertion_point(field_get:lm.connected_msg.recv_id)
  return recv_id_;
}
inline void connected_msg::set_recv_id(::google::protobuf::int32 value) {
  set_has_recv_id();
  recv_id_ = value;
  // @@protoc_insertion_point(field_set:lm.connected_msg.recv_id)
}

// required string msg = 4;
inline bool connected_msg::has_msg() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void connected_msg::set_has_msg() {
  _has_bits_[0] |= 0x00000008u;
}
inline void connected_msg::clear_has_msg() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void connected_msg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& connected_msg::msg() const {
  // @@protoc_insertion_point(field_get:lm.connected_msg.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void connected_msg::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.connected_msg.msg)
}
inline void connected_msg::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.connected_msg.msg)
}
inline void connected_msg::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.connected_msg.msg)
}
inline ::std::string* connected_msg::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:lm.connected_msg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* connected_msg::release_msg() {
  // @@protoc_insertion_point(field_release:lm.connected_msg.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void connected_msg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:lm.connected_msg.msg)
}

inline const connected_msg* connected_msg::internal_default_instance() {
  return &connected_msg_default_instance_.get();
}
// -------------------------------------------------------------------

// net_msg

// required int32 v = 1;
inline bool net_msg::has_v() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void net_msg::set_has_v() {
  _has_bits_[0] |= 0x00000001u;
}
inline void net_msg::clear_has_v() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void net_msg::clear_v() {
  v_ = 0;
  clear_has_v();
}
inline ::google::protobuf::int32 net_msg::v() const {
  // @@protoc_insertion_point(field_get:lm.net_msg.v)
  return v_;
}
inline void net_msg::set_v(::google::protobuf::int32 value) {
  set_has_v();
  v_ = value;
  // @@protoc_insertion_point(field_set:lm.net_msg.v)
}

// required int32 m_id = 2;
inline bool net_msg::has_m_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void net_msg::set_has_m_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void net_msg::clear_has_m_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void net_msg::clear_m_id() {
  m_id_ = 0;
  clear_has_m_id();
}
inline ::google::protobuf::int32 net_msg::m_id() const {
  // @@protoc_insertion_point(field_get:lm.net_msg.m_id)
  return m_id_;
}
inline void net_msg::set_m_id(::google::protobuf::int32 value) {
  set_has_m_id();
  m_id_ = value;
  // @@protoc_insertion_point(field_set:lm.net_msg.m_id)
}

// required int32 s_id = 3;
inline bool net_msg::has_s_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void net_msg::set_has_s_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void net_msg::clear_has_s_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void net_msg::clear_s_id() {
  s_id_ = 0;
  clear_has_s_id();
}
inline ::google::protobuf::int32 net_msg::s_id() const {
  // @@protoc_insertion_point(field_get:lm.net_msg.s_id)
  return s_id_;
}
inline void net_msg::set_s_id(::google::protobuf::int32 value) {
  set_has_s_id();
  s_id_ = value;
  // @@protoc_insertion_point(field_set:lm.net_msg.s_id)
}

// required int32 opt = 4;
inline bool net_msg::has_opt() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void net_msg::set_has_opt() {
  _has_bits_[0] |= 0x00000008u;
}
inline void net_msg::clear_has_opt() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void net_msg::clear_opt() {
  opt_ = 0;
  clear_has_opt();
}
inline ::google::protobuf::int32 net_msg::opt() const {
  // @@protoc_insertion_point(field_get:lm.net_msg.opt)
  return opt_;
}
inline void net_msg::set_opt(::google::protobuf::int32 value) {
  set_has_opt();
  opt_ = value;
  // @@protoc_insertion_point(field_set:lm.net_msg.opt)
}

// optional string data = 5;
inline bool net_msg::has_data() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void net_msg::set_has_data() {
  _has_bits_[0] |= 0x00000010u;
}
inline void net_msg::clear_has_data() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void net_msg::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& net_msg::data() const {
  // @@protoc_insertion_point(field_get:lm.net_msg.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void net_msg::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.net_msg.data)
}
inline void net_msg::set_data(const char* value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.net_msg.data)
}
inline void net_msg::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.net_msg.data)
}
inline ::std::string* net_msg::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:lm.net_msg.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* net_msg::release_data() {
  // @@protoc_insertion_point(field_release:lm.net_msg.data)
  clear_has_data();
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void net_msg::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:lm.net_msg.data)
}

inline const net_msg* net_msg::internal_default_instance() {
  return &net_msg_default_instance_.get();
}
// -------------------------------------------------------------------

// chat_msg

// required int32 from_id = 1;
inline bool chat_msg::has_from_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void chat_msg::set_has_from_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void chat_msg::clear_has_from_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void chat_msg::clear_from_id() {
  from_id_ = 0;
  clear_has_from_id();
}
inline ::google::protobuf::int32 chat_msg::from_id() const {
  // @@protoc_insertion_point(field_get:lm.chat_msg.from_id)
  return from_id_;
}
inline void chat_msg::set_from_id(::google::protobuf::int32 value) {
  set_has_from_id();
  from_id_ = value;
  // @@protoc_insertion_point(field_set:lm.chat_msg.from_id)
}

// required int32 recv_id = 2;
inline bool chat_msg::has_recv_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void chat_msg::set_has_recv_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void chat_msg::clear_has_recv_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void chat_msg::clear_recv_id() {
  recv_id_ = 0;
  clear_has_recv_id();
}
inline ::google::protobuf::int32 chat_msg::recv_id() const {
  // @@protoc_insertion_point(field_get:lm.chat_msg.recv_id)
  return recv_id_;
}
inline void chat_msg::set_recv_id(::google::protobuf::int32 value) {
  set_has_recv_id();
  recv_id_ = value;
  // @@protoc_insertion_point(field_set:lm.chat_msg.recv_id)
}

// required string msg = 3;
inline bool chat_msg::has_msg() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void chat_msg::set_has_msg() {
  _has_bits_[0] |= 0x00000004u;
}
inline void chat_msg::clear_has_msg() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void chat_msg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& chat_msg::msg() const {
  // @@protoc_insertion_point(field_get:lm.chat_msg.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void chat_msg::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.chat_msg.msg)
}
inline void chat_msg::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.chat_msg.msg)
}
inline void chat_msg::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.chat_msg.msg)
}
inline ::std::string* chat_msg::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:lm.chat_msg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* chat_msg::release_msg() {
  // @@protoc_insertion_point(field_release:lm.chat_msg.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void chat_msg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:lm.chat_msg.msg)
}

inline const chat_msg* chat_msg::internal_default_instance() {
  return &chat_msg_default_instance_.get();
}
// -------------------------------------------------------------------

// join_room_msg

// required int32 u_id = 1;
inline bool join_room_msg::has_u_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void join_room_msg::set_has_u_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void join_room_msg::clear_has_u_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void join_room_msg::clear_u_id() {
  u_id_ = 0;
  clear_has_u_id();
}
inline ::google::protobuf::int32 join_room_msg::u_id() const {
  // @@protoc_insertion_point(field_get:lm.join_room_msg.u_id)
  return u_id_;
}
inline void join_room_msg::set_u_id(::google::protobuf::int32 value) {
  set_has_u_id();
  u_id_ = value;
  // @@protoc_insertion_point(field_set:lm.join_room_msg.u_id)
}

// required string msg = 2;
inline bool join_room_msg::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void join_room_msg::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void join_room_msg::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void join_room_msg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& join_room_msg::msg() const {
  // @@protoc_insertion_point(field_get:lm.join_room_msg.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void join_room_msg::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.join_room_msg.msg)
}
inline void join_room_msg::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.join_room_msg.msg)
}
inline void join_room_msg::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.join_room_msg.msg)
}
inline ::std::string* join_room_msg::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:lm.join_room_msg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* join_room_msg::release_msg() {
  // @@protoc_insertion_point(field_release:lm.join_room_msg.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void join_room_msg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:lm.join_room_msg.msg)
}

inline const join_room_msg* join_room_msg::internal_default_instance() {
  return &join_room_msg_default_instance_.get();
}
// -------------------------------------------------------------------

// leave_room_msg

// required int32 u_id = 1;
inline bool leave_room_msg::has_u_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void leave_room_msg::set_has_u_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void leave_room_msg::clear_has_u_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void leave_room_msg::clear_u_id() {
  u_id_ = 0;
  clear_has_u_id();
}
inline ::google::protobuf::int32 leave_room_msg::u_id() const {
  // @@protoc_insertion_point(field_get:lm.leave_room_msg.u_id)
  return u_id_;
}
inline void leave_room_msg::set_u_id(::google::protobuf::int32 value) {
  set_has_u_id();
  u_id_ = value;
  // @@protoc_insertion_point(field_set:lm.leave_room_msg.u_id)
}

// required string msg = 2;
inline bool leave_room_msg::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void leave_room_msg::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void leave_room_msg::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void leave_room_msg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& leave_room_msg::msg() const {
  // @@protoc_insertion_point(field_get:lm.leave_room_msg.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void leave_room_msg::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.leave_room_msg.msg)
}
inline void leave_room_msg::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.leave_room_msg.msg)
}
inline void leave_room_msg::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.leave_room_msg.msg)
}
inline ::std::string* leave_room_msg::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:lm.leave_room_msg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* leave_room_msg::release_msg() {
  // @@protoc_insertion_point(field_release:lm.leave_room_msg.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void leave_room_msg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:lm.leave_room_msg.msg)
}

inline const leave_room_msg* leave_room_msg::internal_default_instance() {
  return &leave_room_msg_default_instance_.get();
}
// -------------------------------------------------------------------

// sit_msg

// required int32 u_id = 1;
inline bool sit_msg::has_u_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void sit_msg::set_has_u_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void sit_msg::clear_has_u_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void sit_msg::clear_u_id() {
  u_id_ = 0;
  clear_has_u_id();
}
inline ::google::protobuf::int32 sit_msg::u_id() const {
  // @@protoc_insertion_point(field_get:lm.sit_msg.u_id)
  return u_id_;
}
inline void sit_msg::set_u_id(::google::protobuf::int32 value) {
  set_has_u_id();
  u_id_ = value;
  // @@protoc_insertion_point(field_set:lm.sit_msg.u_id)
}

// required string msg = 2;
inline bool sit_msg::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void sit_msg::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void sit_msg::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void sit_msg::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& sit_msg::msg() const {
  // @@protoc_insertion_point(field_get:lm.sit_msg.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void sit_msg::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.sit_msg.msg)
}
inline void sit_msg::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.sit_msg.msg)
}
inline void sit_msg::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.sit_msg.msg)
}
inline ::std::string* sit_msg::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:lm.sit_msg.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* sit_msg::release_msg() {
  // @@protoc_insertion_point(field_release:lm.sit_msg.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void sit_msg::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:lm.sit_msg.msg)
}

inline const sit_msg* sit_msg::internal_default_instance() {
  return &sit_msg_default_instance_.get();
}
// -------------------------------------------------------------------

// UserInfo_msg

// required int32 u_age = 1;
inline bool UserInfo_msg::has_u_age() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserInfo_msg::set_has_u_age() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserInfo_msg::clear_has_u_age() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserInfo_msg::clear_u_age() {
  u_age_ = 0;
  clear_has_u_age();
}
inline ::google::protobuf::int32 UserInfo_msg::u_age() const {
  // @@protoc_insertion_point(field_get:lm.UserInfo_msg.u_age)
  return u_age_;
}
inline void UserInfo_msg::set_u_age(::google::protobuf::int32 value) {
  set_has_u_age();
  u_age_ = value;
  // @@protoc_insertion_point(field_set:lm.UserInfo_msg.u_age)
}

// required int32 u_sex = 2;
inline bool UserInfo_msg::has_u_sex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserInfo_msg::set_has_u_sex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserInfo_msg::clear_has_u_sex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserInfo_msg::clear_u_sex() {
  u_sex_ = 0;
  clear_has_u_sex();
}
inline ::google::protobuf::int32 UserInfo_msg::u_sex() const {
  // @@protoc_insertion_point(field_get:lm.UserInfo_msg.u_sex)
  return u_sex_;
}
inline void UserInfo_msg::set_u_sex(::google::protobuf::int32 value) {
  set_has_u_sex();
  u_sex_ = value;
  // @@protoc_insertion_point(field_set:lm.UserInfo_msg.u_sex)
}

// required string u_name = 3;
inline bool UserInfo_msg::has_u_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserInfo_msg::set_has_u_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserInfo_msg::clear_has_u_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserInfo_msg::clear_u_name() {
  u_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_u_name();
}
inline const ::std::string& UserInfo_msg::u_name() const {
  // @@protoc_insertion_point(field_get:lm.UserInfo_msg.u_name)
  return u_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo_msg::set_u_name(const ::std::string& value) {
  set_has_u_name();
  u_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.UserInfo_msg.u_name)
}
inline void UserInfo_msg::set_u_name(const char* value) {
  set_has_u_name();
  u_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.UserInfo_msg.u_name)
}
inline void UserInfo_msg::set_u_name(const char* value, size_t size) {
  set_has_u_name();
  u_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.UserInfo_msg.u_name)
}
inline ::std::string* UserInfo_msg::mutable_u_name() {
  set_has_u_name();
  // @@protoc_insertion_point(field_mutable:lm.UserInfo_msg.u_name)
  return u_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserInfo_msg::release_u_name() {
  // @@protoc_insertion_point(field_release:lm.UserInfo_msg.u_name)
  clear_has_u_name();
  return u_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo_msg::set_allocated_u_name(::std::string* u_name) {
  if (u_name != NULL) {
    set_has_u_name();
  } else {
    clear_has_u_name();
  }
  u_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), u_name);
  // @@protoc_insertion_point(field_set_allocated:lm.UserInfo_msg.u_name)
}

// required string u_address = 4;
inline bool UserInfo_msg::has_u_address() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UserInfo_msg::set_has_u_address() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UserInfo_msg::clear_has_u_address() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UserInfo_msg::clear_u_address() {
  u_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_u_address();
}
inline const ::std::string& UserInfo_msg::u_address() const {
  // @@protoc_insertion_point(field_get:lm.UserInfo_msg.u_address)
  return u_address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo_msg::set_u_address(const ::std::string& value) {
  set_has_u_address();
  u_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:lm.UserInfo_msg.u_address)
}
inline void UserInfo_msg::set_u_address(const char* value) {
  set_has_u_address();
  u_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:lm.UserInfo_msg.u_address)
}
inline void UserInfo_msg::set_u_address(const char* value, size_t size) {
  set_has_u_address();
  u_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:lm.UserInfo_msg.u_address)
}
inline ::std::string* UserInfo_msg::mutable_u_address() {
  set_has_u_address();
  // @@protoc_insertion_point(field_mutable:lm.UserInfo_msg.u_address)
  return u_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserInfo_msg::release_u_address() {
  // @@protoc_insertion_point(field_release:lm.UserInfo_msg.u_address)
  clear_has_u_address();
  return u_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfo_msg::set_allocated_u_address(::std::string* u_address) {
  if (u_address != NULL) {
    set_has_u_address();
  } else {
    clear_has_u_address();
  }
  u_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), u_address);
  // @@protoc_insertion_point(field_set_allocated:lm.UserInfo_msg.u_address)
}

inline const UserInfo_msg* UserInfo_msg::internal_default_instance() {
  return &UserInfo_msg_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace lm

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lm_2eproto__INCLUDED
