// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#ifndef PROTOBUF_game_2eproto__INCLUDED
#define PROTOBUF_game_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace msg {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_game_2eproto();
void protobuf_InitDefaults_game_2eproto();
void protobuf_AssignDesc_game_2eproto();
void protobuf_ShutdownFile_game_2eproto();

class game_msg_end_reponse;
class game_msg_sitdown_reponse;
class game_msg_sitdown_request;
class game_msg_situp_reponse;
class game_msg_situp_request;
class game_msg_start_reponse;

// ===================================================================

class game_msg_start_reponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.game_msg_start_reponse) */ {
 public:
  game_msg_start_reponse();
  virtual ~game_msg_start_reponse();

  game_msg_start_reponse(const game_msg_start_reponse& from);

  inline game_msg_start_reponse& operator=(const game_msg_start_reponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_msg_start_reponse& default_instance();

  static const game_msg_start_reponse* internal_default_instance();

  void Swap(game_msg_start_reponse* other);

  // implements Message ----------------------------------------------

  inline game_msg_start_reponse* New() const { return New(NULL); }

  game_msg_start_reponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_msg_start_reponse& from);
  void MergeFrom(const game_msg_start_reponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(game_msg_start_reponse* other);
  void UnsafeMergeFrom(const game_msg_start_reponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msg.game_msg_start_reponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_game_2eproto_impl();
  friend void  protobuf_AddDesc_game_2eproto_impl();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<game_msg_start_reponse> game_msg_start_reponse_default_instance_;

// -------------------------------------------------------------------

class game_msg_end_reponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.game_msg_end_reponse) */ {
 public:
  game_msg_end_reponse();
  virtual ~game_msg_end_reponse();

  game_msg_end_reponse(const game_msg_end_reponse& from);

  inline game_msg_end_reponse& operator=(const game_msg_end_reponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_msg_end_reponse& default_instance();

  static const game_msg_end_reponse* internal_default_instance();

  void Swap(game_msg_end_reponse* other);

  // implements Message ----------------------------------------------

  inline game_msg_end_reponse* New() const { return New(NULL); }

  game_msg_end_reponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_msg_end_reponse& from);
  void MergeFrom(const game_msg_end_reponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(game_msg_end_reponse* other);
  void UnsafeMergeFrom(const game_msg_end_reponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:msg.game_msg_end_reponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 state_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_game_2eproto_impl();
  friend void  protobuf_AddDesc_game_2eproto_impl();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<game_msg_end_reponse> game_msg_end_reponse_default_instance_;

// -------------------------------------------------------------------

class game_msg_situp_request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.game_msg_situp_request) */ {
 public:
  game_msg_situp_request();
  virtual ~game_msg_situp_request();

  game_msg_situp_request(const game_msg_situp_request& from);

  inline game_msg_situp_request& operator=(const game_msg_situp_request& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_msg_situp_request& default_instance();

  static const game_msg_situp_request* internal_default_instance();

  void Swap(game_msg_situp_request* other);

  // implements Message ----------------------------------------------

  inline game_msg_situp_request* New() const { return New(NULL); }

  game_msg_situp_request* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_msg_situp_request& from);
  void MergeFrom(const game_msg_situp_request& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(game_msg_situp_request* other);
  void UnsafeMergeFrom(const game_msg_situp_request& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // optional int32 seat = 2;
  void clear_seat();
  static const int kSeatFieldNumber = 2;
  ::google::protobuf::int32 seat() const;
  void set_seat(::google::protobuf::int32 value);

  // optional bool lookup = 3;
  void clear_lookup();
  static const int kLookupFieldNumber = 3;
  bool lookup() const;
  void set_lookup(bool value);

  // @@protoc_insertion_point(class_scope:msg.game_msg_situp_request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 seat_;
  bool lookup_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_game_2eproto_impl();
  friend void  protobuf_AddDesc_game_2eproto_impl();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<game_msg_situp_request> game_msg_situp_request_default_instance_;

// -------------------------------------------------------------------

class game_msg_situp_reponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.game_msg_situp_reponse) */ {
 public:
  game_msg_situp_reponse();
  virtual ~game_msg_situp_reponse();

  game_msg_situp_reponse(const game_msg_situp_reponse& from);

  inline game_msg_situp_reponse& operator=(const game_msg_situp_reponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_msg_situp_reponse& default_instance();

  static const game_msg_situp_reponse* internal_default_instance();

  void Swap(game_msg_situp_reponse* other);

  // implements Message ----------------------------------------------

  inline game_msg_situp_reponse* New() const { return New(NULL); }

  game_msg_situp_reponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_msg_situp_reponse& from);
  void MergeFrom(const game_msg_situp_reponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(game_msg_situp_reponse* other);
  void UnsafeMergeFrom(const game_msg_situp_reponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // optional int32 seat = 2;
  void clear_seat();
  static const int kSeatFieldNumber = 2;
  ::google::protobuf::int32 seat() const;
  void set_seat(::google::protobuf::int32 value);

  // optional bool lookup = 3;
  void clear_lookup();
  static const int kLookupFieldNumber = 3;
  bool lookup() const;
  void set_lookup(bool value);

  // @@protoc_insertion_point(class_scope:msg.game_msg_situp_reponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 seat_;
  bool lookup_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_game_2eproto_impl();
  friend void  protobuf_AddDesc_game_2eproto_impl();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<game_msg_situp_reponse> game_msg_situp_reponse_default_instance_;

// -------------------------------------------------------------------

class game_msg_sitdown_request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.game_msg_sitdown_request) */ {
 public:
  game_msg_sitdown_request();
  virtual ~game_msg_sitdown_request();

  game_msg_sitdown_request(const game_msg_sitdown_request& from);

  inline game_msg_sitdown_request& operator=(const game_msg_sitdown_request& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_msg_sitdown_request& default_instance();

  static const game_msg_sitdown_request* internal_default_instance();

  void Swap(game_msg_sitdown_request* other);

  // implements Message ----------------------------------------------

  inline game_msg_sitdown_request* New() const { return New(NULL); }

  game_msg_sitdown_request* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_msg_sitdown_request& from);
  void MergeFrom(const game_msg_sitdown_request& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(game_msg_sitdown_request* other);
  void UnsafeMergeFrom(const game_msg_sitdown_request& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // optional int32 seat = 2;
  void clear_seat();
  static const int kSeatFieldNumber = 2;
  ::google::protobuf::int32 seat() const;
  void set_seat(::google::protobuf::int32 value);

  // optional bool lookup = 3;
  void clear_lookup();
  static const int kLookupFieldNumber = 3;
  bool lookup() const;
  void set_lookup(bool value);

  // @@protoc_insertion_point(class_scope:msg.game_msg_sitdown_request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 seat_;
  bool lookup_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_game_2eproto_impl();
  friend void  protobuf_AddDesc_game_2eproto_impl();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<game_msg_sitdown_request> game_msg_sitdown_request_default_instance_;

// -------------------------------------------------------------------

class game_msg_sitdown_reponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:msg.game_msg_sitdown_reponse) */ {
 public:
  game_msg_sitdown_reponse();
  virtual ~game_msg_sitdown_reponse();

  game_msg_sitdown_reponse(const game_msg_sitdown_reponse& from);

  inline game_msg_sitdown_reponse& operator=(const game_msg_sitdown_reponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_msg_sitdown_reponse& default_instance();

  static const game_msg_sitdown_reponse* internal_default_instance();

  void Swap(game_msg_sitdown_reponse* other);

  // implements Message ----------------------------------------------

  inline game_msg_sitdown_reponse* New() const { return New(NULL); }

  game_msg_sitdown_reponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_msg_sitdown_reponse& from);
  void MergeFrom(const game_msg_sitdown_reponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(game_msg_sitdown_reponse* other);
  void UnsafeMergeFrom(const game_msg_sitdown_reponse& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // optional int32 seat = 2;
  void clear_seat();
  static const int kSeatFieldNumber = 2;
  ::google::protobuf::int32 seat() const;
  void set_seat(::google::protobuf::int32 value);

  // optional bool lookup = 3;
  void clear_lookup();
  static const int kLookupFieldNumber = 3;
  bool lookup() const;
  void set_lookup(bool value);

  // @@protoc_insertion_point(class_scope:msg.game_msg_sitdown_reponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 uid_;
  ::google::protobuf::int32 seat_;
  bool lookup_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_game_2eproto_impl();
  friend void  protobuf_AddDesc_game_2eproto_impl();
  friend void protobuf_AssignDesc_game_2eproto();
  friend void protobuf_ShutdownFile_game_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<game_msg_sitdown_reponse> game_msg_sitdown_reponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// game_msg_start_reponse

// optional int32 state = 1;
inline void game_msg_start_reponse::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 game_msg_start_reponse::state() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_start_reponse.state)
  return state_;
}
inline void game_msg_start_reponse::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_start_reponse.state)
}

inline const game_msg_start_reponse* game_msg_start_reponse::internal_default_instance() {
  return &game_msg_start_reponse_default_instance_.get();
}
// -------------------------------------------------------------------

// game_msg_end_reponse

// optional int32 state = 1;
inline void game_msg_end_reponse::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 game_msg_end_reponse::state() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_end_reponse.state)
  return state_;
}
inline void game_msg_end_reponse::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_end_reponse.state)
}

inline const game_msg_end_reponse* game_msg_end_reponse::internal_default_instance() {
  return &game_msg_end_reponse_default_instance_.get();
}
// -------------------------------------------------------------------

// game_msg_situp_request

// optional int32 uid = 1;
inline void game_msg_situp_request::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 game_msg_situp_request::uid() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_situp_request.uid)
  return uid_;
}
inline void game_msg_situp_request::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_situp_request.uid)
}

// optional int32 seat = 2;
inline void game_msg_situp_request::clear_seat() {
  seat_ = 0;
}
inline ::google::protobuf::int32 game_msg_situp_request::seat() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_situp_request.seat)
  return seat_;
}
inline void game_msg_situp_request::set_seat(::google::protobuf::int32 value) {
  
  seat_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_situp_request.seat)
}

// optional bool lookup = 3;
inline void game_msg_situp_request::clear_lookup() {
  lookup_ = false;
}
inline bool game_msg_situp_request::lookup() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_situp_request.lookup)
  return lookup_;
}
inline void game_msg_situp_request::set_lookup(bool value) {
  
  lookup_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_situp_request.lookup)
}

inline const game_msg_situp_request* game_msg_situp_request::internal_default_instance() {
  return &game_msg_situp_request_default_instance_.get();
}
// -------------------------------------------------------------------

// game_msg_situp_reponse

// optional int32 uid = 1;
inline void game_msg_situp_reponse::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 game_msg_situp_reponse::uid() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_situp_reponse.uid)
  return uid_;
}
inline void game_msg_situp_reponse::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_situp_reponse.uid)
}

// optional int32 seat = 2;
inline void game_msg_situp_reponse::clear_seat() {
  seat_ = 0;
}
inline ::google::protobuf::int32 game_msg_situp_reponse::seat() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_situp_reponse.seat)
  return seat_;
}
inline void game_msg_situp_reponse::set_seat(::google::protobuf::int32 value) {
  
  seat_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_situp_reponse.seat)
}

// optional bool lookup = 3;
inline void game_msg_situp_reponse::clear_lookup() {
  lookup_ = false;
}
inline bool game_msg_situp_reponse::lookup() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_situp_reponse.lookup)
  return lookup_;
}
inline void game_msg_situp_reponse::set_lookup(bool value) {
  
  lookup_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_situp_reponse.lookup)
}

inline const game_msg_situp_reponse* game_msg_situp_reponse::internal_default_instance() {
  return &game_msg_situp_reponse_default_instance_.get();
}
// -------------------------------------------------------------------

// game_msg_sitdown_request

// optional int32 uid = 1;
inline void game_msg_sitdown_request::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 game_msg_sitdown_request::uid() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_sitdown_request.uid)
  return uid_;
}
inline void game_msg_sitdown_request::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_sitdown_request.uid)
}

// optional int32 seat = 2;
inline void game_msg_sitdown_request::clear_seat() {
  seat_ = 0;
}
inline ::google::protobuf::int32 game_msg_sitdown_request::seat() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_sitdown_request.seat)
  return seat_;
}
inline void game_msg_sitdown_request::set_seat(::google::protobuf::int32 value) {
  
  seat_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_sitdown_request.seat)
}

// optional bool lookup = 3;
inline void game_msg_sitdown_request::clear_lookup() {
  lookup_ = false;
}
inline bool game_msg_sitdown_request::lookup() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_sitdown_request.lookup)
  return lookup_;
}
inline void game_msg_sitdown_request::set_lookup(bool value) {
  
  lookup_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_sitdown_request.lookup)
}

inline const game_msg_sitdown_request* game_msg_sitdown_request::internal_default_instance() {
  return &game_msg_sitdown_request_default_instance_.get();
}
// -------------------------------------------------------------------

// game_msg_sitdown_reponse

// optional int32 uid = 1;
inline void game_msg_sitdown_reponse::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 game_msg_sitdown_reponse::uid() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_sitdown_reponse.uid)
  return uid_;
}
inline void game_msg_sitdown_reponse::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_sitdown_reponse.uid)
}

// optional int32 seat = 2;
inline void game_msg_sitdown_reponse::clear_seat() {
  seat_ = 0;
}
inline ::google::protobuf::int32 game_msg_sitdown_reponse::seat() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_sitdown_reponse.seat)
  return seat_;
}
inline void game_msg_sitdown_reponse::set_seat(::google::protobuf::int32 value) {
  
  seat_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_sitdown_reponse.seat)
}

// optional bool lookup = 3;
inline void game_msg_sitdown_reponse::clear_lookup() {
  lookup_ = false;
}
inline bool game_msg_sitdown_reponse::lookup() const {
  // @@protoc_insertion_point(field_get:msg.game_msg_sitdown_reponse.lookup)
  return lookup_;
}
inline void game_msg_sitdown_reponse::set_lookup(bool value) {
  
  lookup_ = value;
  // @@protoc_insertion_point(field_set:msg.game_msg_sitdown_reponse.lookup)
}

inline const game_msg_sitdown_reponse* game_msg_sitdown_reponse::internal_default_instance() {
  return &game_msg_sitdown_reponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_game_2eproto__INCLUDED
