// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform.proto

#ifndef PROTOBUF_platform_2eproto__INCLUDED
#define PROTOBUF_platform_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace platform {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_platform_2eproto();
void protobuf_InitDefaults_platform_2eproto();
void protobuf_AssignDesc_platform_2eproto();
void protobuf_ShutdownFile_platform_2eproto();

class cs_msg_chat;
class cs_msg_login;
class cs_msg_logout;
class csc_msg_heartbeat;
class sc_msg_servertime;
class sc_msg_userinfo;

// ===================================================================

class csc_msg_heartbeat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:platform.csc_msg_heartbeat) */ {
 public:
  csc_msg_heartbeat();
  virtual ~csc_msg_heartbeat();

  csc_msg_heartbeat(const csc_msg_heartbeat& from);

  inline csc_msg_heartbeat& operator=(const csc_msg_heartbeat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const csc_msg_heartbeat& default_instance();

  static const csc_msg_heartbeat* internal_default_instance();

  void Swap(csc_msg_heartbeat* other);

  // implements Message ----------------------------------------------

  inline csc_msg_heartbeat* New() const { return New(NULL); }

  csc_msg_heartbeat* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const csc_msg_heartbeat& from);
  void MergeFrom(const csc_msg_heartbeat& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(csc_msg_heartbeat* other);
  void UnsafeMergeFrom(const csc_msg_heartbeat& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 order = 1;
  bool has_order() const;
  void clear_order();
  static const int kOrderFieldNumber = 1;
  ::google::protobuf::int32 order() const;
  void set_order(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:platform.csc_msg_heartbeat)
 private:
  inline void set_has_order();
  inline void clear_has_order();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 order_;
  friend void  protobuf_InitDefaults_platform_2eproto_impl();
  friend void  protobuf_AddDesc_platform_2eproto_impl();
  friend void protobuf_AssignDesc_platform_2eproto();
  friend void protobuf_ShutdownFile_platform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<csc_msg_heartbeat> csc_msg_heartbeat_default_instance_;

// -------------------------------------------------------------------

class sc_msg_servertime : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:platform.sc_msg_servertime) */ {
 public:
  sc_msg_servertime();
  virtual ~sc_msg_servertime();

  sc_msg_servertime(const sc_msg_servertime& from);

  inline sc_msg_servertime& operator=(const sc_msg_servertime& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const sc_msg_servertime& default_instance();

  static const sc_msg_servertime* internal_default_instance();

  void Swap(sc_msg_servertime* other);

  // implements Message ----------------------------------------------

  inline sc_msg_servertime* New() const { return New(NULL); }

  sc_msg_servertime* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const sc_msg_servertime& from);
  void MergeFrom(const sc_msg_servertime& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(sc_msg_servertime* other);
  void UnsafeMergeFrom(const sc_msg_servertime& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 time = 1;
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 1;
  ::google::protobuf::int32 time() const;
  void set_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:platform.sc_msg_servertime)
 private:
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 time_;
  friend void  protobuf_InitDefaults_platform_2eproto_impl();
  friend void  protobuf_AddDesc_platform_2eproto_impl();
  friend void protobuf_AssignDesc_platform_2eproto();
  friend void protobuf_ShutdownFile_platform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<sc_msg_servertime> sc_msg_servertime_default_instance_;

// -------------------------------------------------------------------

class cs_msg_login : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:platform.cs_msg_login) */ {
 public:
  cs_msg_login();
  virtual ~cs_msg_login();

  cs_msg_login(const cs_msg_login& from);

  inline cs_msg_login& operator=(const cs_msg_login& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cs_msg_login& default_instance();

  static const cs_msg_login* internal_default_instance();

  void Swap(cs_msg_login* other);

  // implements Message ----------------------------------------------

  inline cs_msg_login* New() const { return New(NULL); }

  cs_msg_login* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cs_msg_login& from);
  void MergeFrom(const cs_msg_login& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(cs_msg_login* other);
  void UnsafeMergeFrom(const cs_msg_login& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 device = 1;
  bool has_device() const;
  void clear_device();
  static const int kDeviceFieldNumber = 1;
  ::google::protobuf::int32 device() const;
  void set_device(::google::protobuf::int32 value);

  // required string username = 2;
  bool has_username() const;
  void clear_username();
  static const int kUsernameFieldNumber = 2;
  const ::std::string& username() const;
  void set_username(const ::std::string& value);
  void set_username(const char* value);
  void set_username(const char* value, size_t size);
  ::std::string* mutable_username();
  ::std::string* release_username();
  void set_allocated_username(::std::string* username);

  // required string userpsd = 3;
  bool has_userpsd() const;
  void clear_userpsd();
  static const int kUserpsdFieldNumber = 3;
  const ::std::string& userpsd() const;
  void set_userpsd(const ::std::string& value);
  void set_userpsd(const char* value);
  void set_userpsd(const char* value, size_t size);
  ::std::string* mutable_userpsd();
  ::std::string* release_userpsd();
  void set_allocated_userpsd(::std::string* userpsd);

  // @@protoc_insertion_point(class_scope:platform.cs_msg_login)
 private:
  inline void set_has_device();
  inline void clear_has_device();
  inline void set_has_username();
  inline void clear_has_username();
  inline void set_has_userpsd();
  inline void clear_has_userpsd();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr username_;
  ::google::protobuf::internal::ArenaStringPtr userpsd_;
  ::google::protobuf::int32 device_;
  friend void  protobuf_InitDefaults_platform_2eproto_impl();
  friend void  protobuf_AddDesc_platform_2eproto_impl();
  friend void protobuf_AssignDesc_platform_2eproto();
  friend void protobuf_ShutdownFile_platform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<cs_msg_login> cs_msg_login_default_instance_;

// -------------------------------------------------------------------

class cs_msg_logout : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:platform.cs_msg_logout) */ {
 public:
  cs_msg_logout();
  virtual ~cs_msg_logout();

  cs_msg_logout(const cs_msg_logout& from);

  inline cs_msg_logout& operator=(const cs_msg_logout& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cs_msg_logout& default_instance();

  static const cs_msg_logout* internal_default_instance();

  void Swap(cs_msg_logout* other);

  // implements Message ----------------------------------------------

  inline cs_msg_logout* New() const { return New(NULL); }

  cs_msg_logout* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cs_msg_logout& from);
  void MergeFrom(const cs_msg_logout& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(cs_msg_logout* other);
  void UnsafeMergeFrom(const cs_msg_logout& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 device = 1;
  bool has_device() const;
  void clear_device();
  static const int kDeviceFieldNumber = 1;
  ::google::protobuf::int32 device() const;
  void set_device(::google::protobuf::int32 value);

  // required int32 from_id = 2;
  bool has_from_id() const;
  void clear_from_id();
  static const int kFromIdFieldNumber = 2;
  ::google::protobuf::int32 from_id() const;
  void set_from_id(::google::protobuf::int32 value);

  // required int32 recv_id = 3;
  bool has_recv_id() const;
  void clear_recv_id();
  static const int kRecvIdFieldNumber = 3;
  ::google::protobuf::int32 recv_id() const;
  void set_recv_id(::google::protobuf::int32 value);

  // required string msg = 4;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 4;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:platform.cs_msg_logout)
 private:
  inline void set_has_device();
  inline void clear_has_device();
  inline void set_has_from_id();
  inline void clear_has_from_id();
  inline void set_has_recv_id();
  inline void clear_has_recv_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 device_;
  ::google::protobuf::int32 from_id_;
  ::google::protobuf::int32 recv_id_;
  friend void  protobuf_InitDefaults_platform_2eproto_impl();
  friend void  protobuf_AddDesc_platform_2eproto_impl();
  friend void protobuf_AssignDesc_platform_2eproto();
  friend void protobuf_ShutdownFile_platform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<cs_msg_logout> cs_msg_logout_default_instance_;

// -------------------------------------------------------------------

class cs_msg_chat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:platform.cs_msg_chat) */ {
 public:
  cs_msg_chat();
  virtual ~cs_msg_chat();

  cs_msg_chat(const cs_msg_chat& from);

  inline cs_msg_chat& operator=(const cs_msg_chat& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cs_msg_chat& default_instance();

  static const cs_msg_chat* internal_default_instance();

  void Swap(cs_msg_chat* other);

  // implements Message ----------------------------------------------

  inline cs_msg_chat* New() const { return New(NULL); }

  cs_msg_chat* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cs_msg_chat& from);
  void MergeFrom(const cs_msg_chat& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(cs_msg_chat* other);
  void UnsafeMergeFrom(const cs_msg_chat& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 device = 1;
  bool has_device() const;
  void clear_device();
  static const int kDeviceFieldNumber = 1;
  ::google::protobuf::int32 device() const;
  void set_device(::google::protobuf::int32 value);

  // required int32 from_id = 2;
  bool has_from_id() const;
  void clear_from_id();
  static const int kFromIdFieldNumber = 2;
  ::google::protobuf::int32 from_id() const;
  void set_from_id(::google::protobuf::int32 value);

  // required int32 recv_id = 3;
  bool has_recv_id() const;
  void clear_recv_id();
  static const int kRecvIdFieldNumber = 3;
  ::google::protobuf::int32 recv_id() const;
  void set_recv_id(::google::protobuf::int32 value);

  // required string msg = 4;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 4;
  const ::std::string& msg() const;
  void set_msg(const ::std::string& value);
  void set_msg(const char* value);
  void set_msg(const char* value, size_t size);
  ::std::string* mutable_msg();
  ::std::string* release_msg();
  void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:platform.cs_msg_chat)
 private:
  inline void set_has_device();
  inline void clear_has_device();
  inline void set_has_from_id();
  inline void clear_has_from_id();
  inline void set_has_recv_id();
  inline void clear_has_recv_id();
  inline void set_has_msg();
  inline void clear_has_msg();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr msg_;
  ::google::protobuf::int32 device_;
  ::google::protobuf::int32 from_id_;
  ::google::protobuf::int32 recv_id_;
  friend void  protobuf_InitDefaults_platform_2eproto_impl();
  friend void  protobuf_AddDesc_platform_2eproto_impl();
  friend void protobuf_AssignDesc_platform_2eproto();
  friend void protobuf_ShutdownFile_platform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<cs_msg_chat> cs_msg_chat_default_instance_;

// -------------------------------------------------------------------

class sc_msg_userinfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:platform.sc_msg_userinfo) */ {
 public:
  sc_msg_userinfo();
  virtual ~sc_msg_userinfo();

  sc_msg_userinfo(const sc_msg_userinfo& from);

  inline sc_msg_userinfo& operator=(const sc_msg_userinfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const sc_msg_userinfo& default_instance();

  static const sc_msg_userinfo* internal_default_instance();

  void Swap(sc_msg_userinfo* other);

  // implements Message ----------------------------------------------

  inline sc_msg_userinfo* New() const { return New(NULL); }

  sc_msg_userinfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const sc_msg_userinfo& from);
  void MergeFrom(const sc_msg_userinfo& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(sc_msg_userinfo* other);
  void UnsafeMergeFrom(const sc_msg_userinfo& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 age = 1;
  bool has_age() const;
  void clear_age();
  static const int kAgeFieldNumber = 1;
  ::google::protobuf::int32 age() const;
  void set_age(::google::protobuf::int32 value);

  // required int32 sex = 2;
  bool has_sex() const;
  void clear_sex();
  static const int kSexFieldNumber = 2;
  ::google::protobuf::int32 sex() const;
  void set_sex(::google::protobuf::int32 value);

  // required string name = 3;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // required string address = 4;
  bool has_address() const;
  void clear_address();
  static const int kAddressFieldNumber = 4;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  void set_address(const char* value);
  void set_address(const char* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // @@protoc_insertion_point(class_scope:platform.sc_msg_userinfo)
 private:
  inline void set_has_age();
  inline void clear_has_age();
  inline void set_has_sex();
  inline void clear_has_sex();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_address();
  inline void clear_has_address();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::int32 age_;
  ::google::protobuf::int32 sex_;
  friend void  protobuf_InitDefaults_platform_2eproto_impl();
  friend void  protobuf_AddDesc_platform_2eproto_impl();
  friend void protobuf_AssignDesc_platform_2eproto();
  friend void protobuf_ShutdownFile_platform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<sc_msg_userinfo> sc_msg_userinfo_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// csc_msg_heartbeat

// required int32 order = 1;
inline bool csc_msg_heartbeat::has_order() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void csc_msg_heartbeat::set_has_order() {
  _has_bits_[0] |= 0x00000001u;
}
inline void csc_msg_heartbeat::clear_has_order() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void csc_msg_heartbeat::clear_order() {
  order_ = 0;
  clear_has_order();
}
inline ::google::protobuf::int32 csc_msg_heartbeat::order() const {
  // @@protoc_insertion_point(field_get:platform.csc_msg_heartbeat.order)
  return order_;
}
inline void csc_msg_heartbeat::set_order(::google::protobuf::int32 value) {
  set_has_order();
  order_ = value;
  // @@protoc_insertion_point(field_set:platform.csc_msg_heartbeat.order)
}

inline const csc_msg_heartbeat* csc_msg_heartbeat::internal_default_instance() {
  return &csc_msg_heartbeat_default_instance_.get();
}
// -------------------------------------------------------------------

// sc_msg_servertime

// required int32 time = 1;
inline bool sc_msg_servertime::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void sc_msg_servertime::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void sc_msg_servertime::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void sc_msg_servertime::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 sc_msg_servertime::time() const {
  // @@protoc_insertion_point(field_get:platform.sc_msg_servertime.time)
  return time_;
}
inline void sc_msg_servertime::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:platform.sc_msg_servertime.time)
}

inline const sc_msg_servertime* sc_msg_servertime::internal_default_instance() {
  return &sc_msg_servertime_default_instance_.get();
}
// -------------------------------------------------------------------

// cs_msg_login

// required int32 device = 1;
inline bool cs_msg_login::has_device() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cs_msg_login::set_has_device() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cs_msg_login::clear_has_device() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cs_msg_login::clear_device() {
  device_ = 0;
  clear_has_device();
}
inline ::google::protobuf::int32 cs_msg_login::device() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_login.device)
  return device_;
}
inline void cs_msg_login::set_device(::google::protobuf::int32 value) {
  set_has_device();
  device_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_login.device)
}

// required string username = 2;
inline bool cs_msg_login::has_username() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void cs_msg_login::set_has_username() {
  _has_bits_[0] |= 0x00000002u;
}
inline void cs_msg_login::clear_has_username() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void cs_msg_login::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_username();
}
inline const ::std::string& cs_msg_login::username() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_login.username)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_login::set_username(const ::std::string& value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:platform.cs_msg_login.username)
}
inline void cs_msg_login::set_username(const char* value) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:platform.cs_msg_login.username)
}
inline void cs_msg_login::set_username(const char* value, size_t size) {
  set_has_username();
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:platform.cs_msg_login.username)
}
inline ::std::string* cs_msg_login::mutable_username() {
  set_has_username();
  // @@protoc_insertion_point(field_mutable:platform.cs_msg_login.username)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* cs_msg_login::release_username() {
  // @@protoc_insertion_point(field_release:platform.cs_msg_login.username)
  clear_has_username();
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_login::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    set_has_username();
  } else {
    clear_has_username();
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:platform.cs_msg_login.username)
}

// required string userpsd = 3;
inline bool cs_msg_login::has_userpsd() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void cs_msg_login::set_has_userpsd() {
  _has_bits_[0] |= 0x00000004u;
}
inline void cs_msg_login::clear_has_userpsd() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void cs_msg_login::clear_userpsd() {
  userpsd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_userpsd();
}
inline const ::std::string& cs_msg_login::userpsd() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_login.userpsd)
  return userpsd_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_login::set_userpsd(const ::std::string& value) {
  set_has_userpsd();
  userpsd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:platform.cs_msg_login.userpsd)
}
inline void cs_msg_login::set_userpsd(const char* value) {
  set_has_userpsd();
  userpsd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:platform.cs_msg_login.userpsd)
}
inline void cs_msg_login::set_userpsd(const char* value, size_t size) {
  set_has_userpsd();
  userpsd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:platform.cs_msg_login.userpsd)
}
inline ::std::string* cs_msg_login::mutable_userpsd() {
  set_has_userpsd();
  // @@protoc_insertion_point(field_mutable:platform.cs_msg_login.userpsd)
  return userpsd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* cs_msg_login::release_userpsd() {
  // @@protoc_insertion_point(field_release:platform.cs_msg_login.userpsd)
  clear_has_userpsd();
  return userpsd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_login::set_allocated_userpsd(::std::string* userpsd) {
  if (userpsd != NULL) {
    set_has_userpsd();
  } else {
    clear_has_userpsd();
  }
  userpsd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userpsd);
  // @@protoc_insertion_point(field_set_allocated:platform.cs_msg_login.userpsd)
}

inline const cs_msg_login* cs_msg_login::internal_default_instance() {
  return &cs_msg_login_default_instance_.get();
}
// -------------------------------------------------------------------

// cs_msg_logout

// required int32 device = 1;
inline bool cs_msg_logout::has_device() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cs_msg_logout::set_has_device() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cs_msg_logout::clear_has_device() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cs_msg_logout::clear_device() {
  device_ = 0;
  clear_has_device();
}
inline ::google::protobuf::int32 cs_msg_logout::device() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_logout.device)
  return device_;
}
inline void cs_msg_logout::set_device(::google::protobuf::int32 value) {
  set_has_device();
  device_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_logout.device)
}

// required int32 from_id = 2;
inline bool cs_msg_logout::has_from_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void cs_msg_logout::set_has_from_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void cs_msg_logout::clear_has_from_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void cs_msg_logout::clear_from_id() {
  from_id_ = 0;
  clear_has_from_id();
}
inline ::google::protobuf::int32 cs_msg_logout::from_id() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_logout.from_id)
  return from_id_;
}
inline void cs_msg_logout::set_from_id(::google::protobuf::int32 value) {
  set_has_from_id();
  from_id_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_logout.from_id)
}

// required int32 recv_id = 3;
inline bool cs_msg_logout::has_recv_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void cs_msg_logout::set_has_recv_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void cs_msg_logout::clear_has_recv_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void cs_msg_logout::clear_recv_id() {
  recv_id_ = 0;
  clear_has_recv_id();
}
inline ::google::protobuf::int32 cs_msg_logout::recv_id() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_logout.recv_id)
  return recv_id_;
}
inline void cs_msg_logout::set_recv_id(::google::protobuf::int32 value) {
  set_has_recv_id();
  recv_id_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_logout.recv_id)
}

// required string msg = 4;
inline bool cs_msg_logout::has_msg() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void cs_msg_logout::set_has_msg() {
  _has_bits_[0] |= 0x00000008u;
}
inline void cs_msg_logout::clear_has_msg() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void cs_msg_logout::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& cs_msg_logout::msg() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_logout.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_logout::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:platform.cs_msg_logout.msg)
}
inline void cs_msg_logout::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:platform.cs_msg_logout.msg)
}
inline void cs_msg_logout::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:platform.cs_msg_logout.msg)
}
inline ::std::string* cs_msg_logout::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:platform.cs_msg_logout.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* cs_msg_logout::release_msg() {
  // @@protoc_insertion_point(field_release:platform.cs_msg_logout.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_logout::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:platform.cs_msg_logout.msg)
}

inline const cs_msg_logout* cs_msg_logout::internal_default_instance() {
  return &cs_msg_logout_default_instance_.get();
}
// -------------------------------------------------------------------

// cs_msg_chat

// required int32 device = 1;
inline bool cs_msg_chat::has_device() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cs_msg_chat::set_has_device() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cs_msg_chat::clear_has_device() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cs_msg_chat::clear_device() {
  device_ = 0;
  clear_has_device();
}
inline ::google::protobuf::int32 cs_msg_chat::device() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_chat.device)
  return device_;
}
inline void cs_msg_chat::set_device(::google::protobuf::int32 value) {
  set_has_device();
  device_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_chat.device)
}

// required int32 from_id = 2;
inline bool cs_msg_chat::has_from_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void cs_msg_chat::set_has_from_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void cs_msg_chat::clear_has_from_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void cs_msg_chat::clear_from_id() {
  from_id_ = 0;
  clear_has_from_id();
}
inline ::google::protobuf::int32 cs_msg_chat::from_id() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_chat.from_id)
  return from_id_;
}
inline void cs_msg_chat::set_from_id(::google::protobuf::int32 value) {
  set_has_from_id();
  from_id_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_chat.from_id)
}

// required int32 recv_id = 3;
inline bool cs_msg_chat::has_recv_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void cs_msg_chat::set_has_recv_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void cs_msg_chat::clear_has_recv_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void cs_msg_chat::clear_recv_id() {
  recv_id_ = 0;
  clear_has_recv_id();
}
inline ::google::protobuf::int32 cs_msg_chat::recv_id() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_chat.recv_id)
  return recv_id_;
}
inline void cs_msg_chat::set_recv_id(::google::protobuf::int32 value) {
  set_has_recv_id();
  recv_id_ = value;
  // @@protoc_insertion_point(field_set:platform.cs_msg_chat.recv_id)
}

// required string msg = 4;
inline bool cs_msg_chat::has_msg() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void cs_msg_chat::set_has_msg() {
  _has_bits_[0] |= 0x00000008u;
}
inline void cs_msg_chat::clear_has_msg() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void cs_msg_chat::clear_msg() {
  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msg();
}
inline const ::std::string& cs_msg_chat::msg() const {
  // @@protoc_insertion_point(field_get:platform.cs_msg_chat.msg)
  return msg_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_chat::set_msg(const ::std::string& value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:platform.cs_msg_chat.msg)
}
inline void cs_msg_chat::set_msg(const char* value) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:platform.cs_msg_chat.msg)
}
inline void cs_msg_chat::set_msg(const char* value, size_t size) {
  set_has_msg();
  msg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:platform.cs_msg_chat.msg)
}
inline ::std::string* cs_msg_chat::mutable_msg() {
  set_has_msg();
  // @@protoc_insertion_point(field_mutable:platform.cs_msg_chat.msg)
  return msg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* cs_msg_chat::release_msg() {
  // @@protoc_insertion_point(field_release:platform.cs_msg_chat.msg)
  clear_has_msg();
  return msg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void cs_msg_chat::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    set_has_msg();
  } else {
    clear_has_msg();
  }
  msg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:platform.cs_msg_chat.msg)
}

inline const cs_msg_chat* cs_msg_chat::internal_default_instance() {
  return &cs_msg_chat_default_instance_.get();
}
// -------------------------------------------------------------------

// sc_msg_userinfo

// required int32 age = 1;
inline bool sc_msg_userinfo::has_age() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void sc_msg_userinfo::set_has_age() {
  _has_bits_[0] |= 0x00000001u;
}
inline void sc_msg_userinfo::clear_has_age() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void sc_msg_userinfo::clear_age() {
  age_ = 0;
  clear_has_age();
}
inline ::google::protobuf::int32 sc_msg_userinfo::age() const {
  // @@protoc_insertion_point(field_get:platform.sc_msg_userinfo.age)
  return age_;
}
inline void sc_msg_userinfo::set_age(::google::protobuf::int32 value) {
  set_has_age();
  age_ = value;
  // @@protoc_insertion_point(field_set:platform.sc_msg_userinfo.age)
}

// required int32 sex = 2;
inline bool sc_msg_userinfo::has_sex() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void sc_msg_userinfo::set_has_sex() {
  _has_bits_[0] |= 0x00000002u;
}
inline void sc_msg_userinfo::clear_has_sex() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void sc_msg_userinfo::clear_sex() {
  sex_ = 0;
  clear_has_sex();
}
inline ::google::protobuf::int32 sc_msg_userinfo::sex() const {
  // @@protoc_insertion_point(field_get:platform.sc_msg_userinfo.sex)
  return sex_;
}
inline void sc_msg_userinfo::set_sex(::google::protobuf::int32 value) {
  set_has_sex();
  sex_ = value;
  // @@protoc_insertion_point(field_set:platform.sc_msg_userinfo.sex)
}

// required string name = 3;
inline bool sc_msg_userinfo::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void sc_msg_userinfo::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void sc_msg_userinfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void sc_msg_userinfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& sc_msg_userinfo::name() const {
  // @@protoc_insertion_point(field_get:platform.sc_msg_userinfo.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void sc_msg_userinfo::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:platform.sc_msg_userinfo.name)
}
inline void sc_msg_userinfo::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:platform.sc_msg_userinfo.name)
}
inline void sc_msg_userinfo::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:platform.sc_msg_userinfo.name)
}
inline ::std::string* sc_msg_userinfo::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:platform.sc_msg_userinfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* sc_msg_userinfo::release_name() {
  // @@protoc_insertion_point(field_release:platform.sc_msg_userinfo.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void sc_msg_userinfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:platform.sc_msg_userinfo.name)
}

// required string address = 4;
inline bool sc_msg_userinfo::has_address() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void sc_msg_userinfo::set_has_address() {
  _has_bits_[0] |= 0x00000008u;
}
inline void sc_msg_userinfo::clear_has_address() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void sc_msg_userinfo::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_address();
}
inline const ::std::string& sc_msg_userinfo::address() const {
  // @@protoc_insertion_point(field_get:platform.sc_msg_userinfo.address)
  return address_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void sc_msg_userinfo::set_address(const ::std::string& value) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:platform.sc_msg_userinfo.address)
}
inline void sc_msg_userinfo::set_address(const char* value) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:platform.sc_msg_userinfo.address)
}
inline void sc_msg_userinfo::set_address(const char* value, size_t size) {
  set_has_address();
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:platform.sc_msg_userinfo.address)
}
inline ::std::string* sc_msg_userinfo::mutable_address() {
  set_has_address();
  // @@protoc_insertion_point(field_mutable:platform.sc_msg_userinfo.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* sc_msg_userinfo::release_address() {
  // @@protoc_insertion_point(field_release:platform.sc_msg_userinfo.address)
  clear_has_address();
  return address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void sc_msg_userinfo::set_allocated_address(::std::string* address) {
  if (address != NULL) {
    set_has_address();
  } else {
    clear_has_address();
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:platform.sc_msg_userinfo.address)
}

inline const sc_msg_userinfo* sc_msg_userinfo::internal_default_instance() {
  return &sc_msg_userinfo_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace platform

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_platform_2eproto__INCLUDED
